project:
  name: qs-workshop
  regions:
  - ap-southeast-1
  - us-east-1
  - us-west-2
  - eu-central-1
tests:
  default:
    template: ./templates/master.template.yaml
    regions:
    - us-east-1

    
    parameters:
      AvailabilityZones: "$[taskcat_getaz_2]"
      EmailAddress: jefteete@cisco.com
      KeyPairName: qsworkshop
      WebserverCIDR: "0.0.0.0/0"
      QSS3KeyPrefix: "quickstart-taskcat-ci/"
      QSS3BucketRegion: "$[taskcat_current_region]"
      QSS3BucketName: "$[aws-quickstart]"

